services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/nginx
      - ${NGINX_SSL}:/etc/ssl/certs
      - ${NGINX_CONF}:/etc/nginx/http.d #dockerfile
#      - ${NGINX_CONF}:/etc/nginx/conf.d #stable
    environment:
      NGINX_HOST: ${DB_HOST}
    networks:
      - lan
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    volumes:
#      - ${VOLUME_WP}:/var/www/html
      - wordpress:/var/www/html #TODO DEBUG
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PWD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WORDPRESS_ADM_USER: ${WP_ADM_USER}
      WORDPRESS_ADM_PASSWORD: ${WP_ADM_PASSWORD}
      WORDPRESS_USER: ${WP_USER}
      WORDPRESS_PASSWORD: ${WP_PASSWORD}
      WORDPRESS_URL: ${WP_URL}
      WORDPRESS_TITLE: ${WP_TITLE}
    networks:
      - lan
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
#    image: mariadb
    build: requirements/mariadb
    volumes:
#      - ${VOLUME_DB}:/var/lib/mysql
      - db:/var/lib/mysql #TODO DEBUG
    expose:
      - ${DB_PORT}
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PWD}
      MARIADB_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
    networks:
      - lan
    restart: on-failure

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - lan
    restart: on-failure

volumes:
  wordpress:
  db:

networks:
  lan:
