services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/nginx
      - ~/goinfre/inception/nginx/ssl:/etc/ssl/certs
      - ~/goinfre/inception/nginx/config:/etc/nginx/conf.d
    networks:
      - lan
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    volumes:
      - ~/goinfre/inception/wordpress:/var/www/html #TODO DEBUG
      - wordpress:/var/www/html
    networks:
      - lan

  mariadb:
    image: mariadb
    volumes:
      - ~/goinfre/inception/mariadb:/var/lib/mysql #TODO DEBUG
      - db:/var/lib/mysql
    expose:
      - ${DB_PORT}
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PWD}
      MARIADB_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
    networks:
      - lan

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - lan

volumes:
  wordpress:
  db:

networks:
  lan:
