services:
  nginx:
    image: nginx
#    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - wordpress:/usr/share/nginx/html
    networks:
      - lan

  wordpress:
    image: wordpress
    ports:
      - "8081:80"
    volumes:
      - ~/goinfre/inception/wordpress:/var/www/html #TODO DEBUG
      - wordpress:/var/www/html
    networks:
        - lan

  mariadb:
    image: mariadb
    volumes:
      - ~/goinfre/inception/mariadb:/var/lib/mysql #TODO DEBUG
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PWD}
      MARIADB_DATABASE: ${DB_NAME}
    networks:
      - lan

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - lan

volumes:
  wordpress:
  db:

networks:
  lan:
