services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/nginx
      - ${NGINX_SSL}:/etc/ssl/certs
      - ${NGINX_CONF}:/etc/nginx/conf.d
    networks:
      - lan
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    volumes:
      - ${VOLUME_WP}:/var/www/html #TODO DEBUG
      - wordpress:/var/www/html
    networks:
      - lan
    restart: on-failure

  mariadb:
    image: mariadb
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql #TODO DEBUG
      - db:/var/lib/mysql
    expose:
      - ${DB_PORT}
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PWD}
      MARIADB_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
    networks:
      - lan
    restart: on-failure

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - lan
    restart: on-failure

volumes:
  wordpress:
  db:

networks:
  lan:
